<?php

namespace App\Notifications;

use App\Models\RentalAgreement;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;

class RentalAgreementPendingNotification extends Notification implements ShouldQueue
{
    use Queueable;

    public function __construct(
        public RentalAgreement $agreement,
    ) {}

    /**
     * Get the notification's delivery channels.
     *
     * When sent to an on-demand (anonymous) route we only use mail.
     * When sent to a real User model we also store it in the database
     * so the tenantʼs bell icon rings.
     *
     * @return array<int, string>
     */
    public function via(object $notifiable): array
    {
        if (method_exists($notifiable, 'getKey')) {
            return ['mail', 'database'];
        }

        return ['mail'];
    }

    /**
     * Get the mail representation of the notification.
     */
    public function toMail(object $notifiable): MailMessage
    {
        $property = $this->agreement->property?->title ?? 'the property';
        $agreementsUrl = config('app.frontend_url', env('FRONTEND_URL', 'http://localhost:5173')).'/account/agreements';

        return (new MailMessage)
            ->subject('Action Required: Rental Agreement Ready for Review')
            ->greeting('Hello, '.$this->agreement->tenant_name.'!')
            ->line("A rental agreement for **{$property}** has been generated by the landlord and is ready for your review.")
            ->line('Please review the terms of the agreement. You can choose to accept and sign the contract or ask questions if you require adjustments.')
            ->action('Review Agreement', $agreementsUrl)
            ->line('Thank you for using '.config('app.name').'!');
    }

    /**
     * Get the array representation of the notification.
     *
     * @return array<string, mixed>
     */
    public function toArray(object $notifiable): array
    {
        return [
            'agreement_id' => $this->agreement->id,
            'property_title' => $this->agreement->property?->title,
            'message' => 'You have a new rental agreement to review for '.($this->agreement->property?->title ?? 'a property').'.',
            'action_url' => '/account/agreements',
        ];
    }
}
